### ISSUE TITLE
Clarify that this code has no relation to the popular FITS viewer with the same name

### ISSUE THREAD

**Issue by divenex** [thusser/qfitswidget#1]
There is a very popular free FITS viewer in astronomy called [QFitsView](https://www.mpe.mpg.de/~ott/QFitsView/). It has become nearly as popular as the classic [DS9](https://ds9.si.edu/). This software has the same name but, as far as I understand, it has no relation to the original QFitsView. The best solution would be to choose a different name, but an alternative would be a clear statement in the README file.

**Comment by thusser** [comment]
I actually wasn't aware of that, thanks for pointint it out! And no, there is no relation. I needed a Qt widget for displaying FITS files in Python and couldn't find any, so I wrote this  -- and qfitsview seemed a logical choice for a Qt FITS viewer widget... Although it's also published on PyPi under the same name, I don't think anyone but me is using it, so renaming it would probably be the best option. Will think of a new name and do that as soon as possible. Thanks again and sorry for any confusion.

**Comment by thusser** [comment]
Just renamed the project to qfitswidget. Thanks again for pointing out the naming conflict.

**Comment by divenex** [comment]
Great. Thank you very much for the quick response.
